baseURL = 'https://lodc2022-culture-art.metadata.moe/'
languageCode = 'ja-jp'
title = '文化・芸術とLOD ハンズオン'

theme = 'book'

[params]
BookRepo = 'https://github.com/Babibubebon/lodc2022-culture-art'
BookCommitPath = 'commit'
BookEditPath = 'edit/master'
BookComments = false